-- MySQL Script generated by MySQL Workbench
-- Sex 17 Nov 2017 12:57:19 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_estagio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_estagio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_estagio` DEFAULT CHARACTER SET utf8 ;
USE `bd_estagio` ;

-- -----------------------------------------------------
-- Table `bd_estagio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_estagio`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_estagio`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_estagio`.`aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `idcurso` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_estagio`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_estagio`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_estagio`.`documentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_estagio`.`documentacao` (
  `iddocumentacao` INT NOT NULL AUTO_INCREMENT,
  `cartaAceite` DATE NOT NULL,
  `formularioRequimento` DATE NOT NULL,
  `termoCompromisso` DATE NOT NULL,
  `comprovanteMatricula` DATE NOT NULL,
  PRIMARY KEY (`iddocumentacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_estagio`.`estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_estagio`.`estagio` (
  `idestagio` INT NOT NULL AUTO_INCREMENT,
  `iddocumentacao` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idAluno` INT NOT NULL,
  `idempresa` INT NOT NULL,
  `nomeAluno` VARCHAR(45) NULL,
  `dataIncio` VARCHAR(45) NOT NULL,
  `ano` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `dataTermino` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`idestagio`),
  INDEX `fk_estagio_usuario_idx` (`idusuario` ASC),
  INDEX `fk_estagio_empresa1_idx` (`idempresa` ASC),
  INDEX `fk_estagio_documentacao1_idx` (`iddocumentacao` ASC),
  INDEX `fk_estagio_aluno1_idx` (`idAluno` ASC),
  CONSTRAINT `fk_estagio_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_estagio`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `bd_estagio`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_documentacao1`
    FOREIGN KEY (`iddocumentacao`)
    REFERENCES `bd_estagio`.`documentacao` (`iddocumentacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `bd_estagio`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
